[tool.pyright]
include = ["Python"]
exclude = ["Python/.venv", "**/__pycache__"]
venvPath = "Python"
venv = ".venv"

# linting handled by ruff
reportUnusedImport = "none"
reportUnusedClass = "none"
reportUnusedFunction = "none"
reportUnusedVariable = "none"

[tool.ruff]
extend-exclude = [".venv", "__pycache__"]
line-length = 88

[tool.ruff.lint]
extend-select = ["I", "B", "UP"]
ignore = [
    "ANN", # typing handled by pyright
]
